name: Firts workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello Wordl of Cats
        run: echo "Hello !! from ${{ github.workflow }} trigerred by the ${{ github.event_name }} by me ${{ github.actor }}"
        
      - name: :*) this is the second change 
        env: 
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done !"
          
